GET http://localhost:5000/notes

###
POST http://localhost:5000/add-notes
Content-Type: application/json

{
    "Title": "Curhat Senin",
    "Content": "Hari Ini Kuis Mobile Mantap"
}

###
PUT http://localhost:5000/edit-notes/1
Content-Type: application/json

{
    "Title": "Catatan pertama Harianku",
    "Content": "Hari Ini Kuliah" 
}

###
DELETE http://localhost:5000/delete-notes/2